// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mendixsso.proxies;

public class MendixSSOSettings
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mendixSSOSettingsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MendixSSO.MendixSSOSettings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SilentAuthentication("SilentAuthentication"),
		AdditionalScopes("AdditionalScopes");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MendixSSOSettings(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MendixSSO.MendixSSOSettings"));
	}

	protected MendixSSOSettings(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixSSOSettingsMendixObject)
	{
		if (mendixSSOSettingsMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MendixSSO.MendixSSOSettings", mendixSSOSettingsMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MendixSSO.MendixSSOSettings");

		this.mendixSSOSettingsMendixObject = mendixSSOSettingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'MendixSSOSettings.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static mendixsso.proxies.MendixSSOSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return mendixsso.proxies.MendixSSOSettings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static mendixsso.proxies.MendixSSOSettings initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mendixsso.proxies.MendixSSOSettings(context, mendixObject);
	}

	public static mendixsso.proxies.MendixSSOSettings load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mendixsso.proxies.MendixSSOSettings.initialize(context, mendixObject);
	}

	public static java.util.List<mendixsso.proxies.MendixSSOSettings> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<mendixsso.proxies.MendixSSOSettings> result = new java.util.ArrayList<mendixsso.proxies.MendixSSOSettings>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MendixSSO.MendixSSOSettings" + xpathConstraint))
			result.add(mendixsso.proxies.MendixSSOSettings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SilentAuthentication
	 */
	public final java.lang.Boolean getSilentAuthentication()
	{
		return getSilentAuthentication(getContext());
	}

	/**
	 * @param context
	 * @return value of SilentAuthentication
	 */
	public final java.lang.Boolean getSilentAuthentication(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SilentAuthentication.toString());
	}

	/**
	 * Set value of SilentAuthentication
	 * @param silentauthentication
	 */
	public final void setSilentAuthentication(java.lang.Boolean silentauthentication)
	{
		setSilentAuthentication(getContext(), silentauthentication);
	}

	/**
	 * Set value of SilentAuthentication
	 * @param context
	 * @param silentauthentication
	 */
	public final void setSilentAuthentication(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean silentauthentication)
	{
		getMendixObject().setValue(context, MemberNames.SilentAuthentication.toString(), silentauthentication);
	}

	/**
	 * @return value of AdditionalScopes
	 */
	public final java.lang.String getAdditionalScopes()
	{
		return getAdditionalScopes(getContext());
	}

	/**
	 * @param context
	 * @return value of AdditionalScopes
	 */
	public final java.lang.String getAdditionalScopes(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdditionalScopes.toString());
	}

	/**
	 * Set value of AdditionalScopes
	 * @param additionalscopes
	 */
	public final void setAdditionalScopes(java.lang.String additionalscopes)
	{
		setAdditionalScopes(getContext(), additionalscopes);
	}

	/**
	 * Set value of AdditionalScopes
	 * @param context
	 * @param additionalscopes
	 */
	public final void setAdditionalScopes(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String additionalscopes)
	{
		getMendixObject().setValue(context, MemberNames.AdditionalScopes.toString(), additionalscopes);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mendixSSOSettingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mendixsso.proxies.MendixSSOSettings that = (mendixsso.proxies.MendixSSOSettings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MendixSSO.MendixSSOSettings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
