// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package deeplink.actions;

import java.awt.List;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IDataType;
import com.mendix.webui.CustomJavaAction;
import deeplink.proxies.KeyValue;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetObjectTypeFromParameter extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String microflowName;

	public GetObjectTypeFromParameter(IContext context, java.lang.String microflowName)
	{
		super(context);
		this.microflowName = microflowName;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		ArrayList<IMendixObject> list = new ArrayList<IMendixObject>(); 
		String[] split = microflowName.split("\\.");
		
		if(split.length > 0) {
			
			IDataType returnType = Core.getReturnType(microflowName);
			Map<String,IDataType> inputParameters = Core.getInputParameters(microflowName);

			inputParameters.forEach((k,v)-> {
				KeyValue kv = new KeyValue(getContext());
				kv.setKey(v.getObjectType());
				list.add(kv.getMendixObject());
			});
		}
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetObjectTypeFromParameter";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
