// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package deeplink.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class SingleParameterDeeplink extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String Microflow;
	private java.lang.String Name;
	private java.lang.Boolean ForceLogin;

	public SingleParameterDeeplink(IContext context, java.lang.String Microflow, java.lang.String Name, java.lang.Boolean ForceLogin)
	{
		super(context);
		this.Microflow = Microflow;
		this.Name = Name;
		this.ForceLogin = ForceLogin;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SingleParameterDeeplink";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
