// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package deeplink.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

/**
 * Starts the deeplink modle. Initializes the "/link/" request handler.
 * 
 * Returns true (always)
 */
public class StartDeeplinkJava extends CustomJavaAction<java.lang.Boolean>
{
	public StartDeeplinkJava(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		Core.addRequestHandler(deeplink.proxies.constants.Constants.getRequestHandlerName()+ "/", new deeplink.implementation.handler.DeeplinkHandler());
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StartDeeplinkJava";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
